TestOnlyPipeline(
	agent: [
		containers: [
			[name: 'golang', image: 'golang:1.25', ttyEnabled: true, command: 'cat', alwaysPullImage: true]
		],
		env       : [
			'GOPRIVATE': 'github.com/zencoder/*, github.com/brightcove/*, *.brightcove.com/*',
		]
	],
	test: [
		stages: [
			[
				name : 'Prepare test environment',
				steps: {
					container('golang') {
						withCredentials([
							string(credentialsId: 'github-public-access-token-bc-svc-cicd', variable: 'GIT_TOKEN')]) {
							sh 'git config --global url."https://$GIT_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"'
							sh 'go mod download'
						}
					}
				}
			],
			[
				name : 'Run Unit Tests',
				steps: {
					container('golang') {
						sh 'make'
					}
				}
			]
		]
	],
	notifications: [slack: "#bolt-dev"]
)
